# Generated by Django 4.1.7 on 2023-03-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_shared_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shared_from',
            field=models.CharField(default='', max_length=100),
        ),
    ]
