# Generated by Django 4.1.7 on 2023-03-31 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_post_shared_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shared_from',
        ),
    ]
