# Generated by Django 4.1.7 on 2023-03-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_post_shared_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_from',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
